openapi: 3.0.0
info:
  title: Lugeasy api docs
  version: v1
  description: 사용자 인증 및 사용자 정보 조회 API 명세서입니다.

servers:
  - url: https://gis0l3wu7c.execute-api.ap-northeast-3.amazonaws.com/dev/api
    description: dev environment

paths:
  /auth/login:
    post:
      summary: 사용자 로그인
      description: 사용자 아이디와 비밀번호 또는 소셜 계정을 통해 로그인하고, 인증 토큰을 발급합니다.
      parameters:
        - in: query
          name: social_type
          schema:
            type: string
            enum: [google, apple]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    id_token:
                      type: string
                      description: id_token
                      example: eyJhbGciOi...
                    client_id:
                      type: string
                      description: client_id
                      example: eyJhbGciOi...
                  required:
                    - id_token
                    - client_id
                - type: object
                  properties:
                    social_token:
                      type: string
                      description: ojoj
                      example: eyJhbGciOi...
                  required:
                    - social_token
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: 인증 토큰
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  refreshToken:
                    type: string
                    description: 리프레시 토큰
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 에러 메시지
                    example: social_type 파라미터가 올바르지 않습니다.
        "401":
          description: 인증 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 에러 메시지
                    example: 소셜 로그인에 실패했습니다.
        "500":
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 에러 메시지
                    example: 서버 내부 오류가 발생했습니다.

  /user:
    get:
      summary: 사용자 정보 조회
      description: 인증된 사용자의 정보를 조회합니다.
      security:
        - BearerAuth: [] # Bearer 토큰 인증 방식 사용 (예시)
      responses:
        "200":
          description: 사용자 정보 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 사용자 ID
                    example: 1
                  username:
                    type: string
                    description: 사용자 아이디
                    example: testuser
                  email:
                    type: string
                    description: 사용자 이메일
                    example: test@example.com
                  # 다른 사용자 정보 필드 추가 가능
        "401":
          description: 인증 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 에러 메시지
                    example: 인증이 필요합니다.
        "404":
          description: 사용자를 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 에러 메시지
                    example: 사용자를 찾을 수 없습니다.
        "500":
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 에러 메시지
                    example: 서버 내부 오류가 발생했습니다.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
