name: Push Swagger YAML to SwaggerHub

on:
  push:
    paths:
      - "swagger.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SwaggerHub CLI
        run: npm install -g swaggerhub-cli

      - name: Configure SwaggerHub CLI
        run: |
          mkdir -p ~/.swaggerhub
          cat <<EOF > ~/.swaggerhub/config.yaml
          apiKey: ${{ secrets.SWAGGERHUB_API_KEY }}
          defaultOwner: lugeasy
          swaggerHubUrl: https://api.swaggerhub.com
          EOF

      - name: Upload to SwaggerHub via CLI
        run: |
          swaggerhub api:update lugeasy/lugeasy-api-docs/1.0.0 \
            --file swagger.yaml \
            --visibility public
            --setdefault
