name: Push Swagger YAML to SwaggerHub

on:
  push:
    paths:
      - "swagger.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SwaggerHub CLI
        run: npm install -g swaggerhub-cli

      - name: Update SwaggerHub API Definition
        run: |
          swaggerhub api:unpublish lugeasy/lugeasy-api-docs/1.0.0
          swaggerhub api:update lugeasy/lugeasy-api-docs/1.0.0 --file swagger.yaml
          swaggerhub api:publish lugeasy/lugeasy-api-docs/1.0.0

