name: Push Swagger YAML to SwaggerHub

on:
  push:
    paths:
      - "swagger.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SwaggerHub CLI
        run: npm install -g swaggerhub-cli

      - name: Upload to SwaggerHub via CLI
        run: |
          swaggerhub api:publish lugeasy/lugeasy-api-docs/1.0.0 \
            --file swagger.yaml \
            --visibility public \
            --publish=publish \
            --setdefault
