name: "Terraform"

on:
    push:
        branches: ["dev"]
    pull_request:

env:
    AWS_REGION: ap-northeast-1

permissions:
    contents: read

jobs:
    terraform:
        name: "Terraform"
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Set up Docker Buildx
              if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
              uses: docker/setup-buildx-action@v2

            - name: Login to ECR
              if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build and push Docker image
              if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
              run: |
                  IMAGE_TAG=latest
                  IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/lugeasy-main-ecr-repo:$IMAGE_TAG
                  docker build -t $IMAGE_URI -f docker/Dockerfile .
                  docker push $IMAGE_URI

            - name: Terraform Init
              run: terraform init
              working-directory: infra

            - name: Terraform Plan
              run: terraform plan -lock=false
              working-directory: infra

            - name: Terraform Apply
              if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
              run: terraform apply -auto-approve
              working-directory: infra

            - name: Update Lambda function code
              if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
              run: |
                  IMAGE_TAG=latest
                  IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/lugeasy-main-ecr-repo:$IMAGE_TAG

                  aws lambda update-function-code \
                    --function-name main_handler \
                    --image-uri $IMAGE_URI \
                    --region ${{ env.AWS_REGION }} \
                    --publish
